"use client";

import * as React from "react";
import { MessagesSquare, Loader2, Sparkles, Lightbulb } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";
import { CopyButton } from "@/components/app/copy-button";
import { cn } from "@/lib/utils";
import type { LaunchPost } from "@/lib/ai/types";
import { draftLaunchPosts } from "@/lib/app-actions";

export function LaunchPostDrafts({ live }: { live: boolean }) {
  const [posts, setPosts] = React.useState<LaunchPost[] | null>(null);
  const [pending, startTransition] = React.useTransition();

  function draft() {
    startTransition(async () => {
      try {
        const result = await draftLaunchPosts();
        setPosts(result);
      } catch {
        setPosts([]);
      }
    });
  }

  return (
    <section className="rounded-2xl border border-line bg-ink-900 p-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-start gap-3">
          <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-line bg-ink-850 text-ember">
            <MessagesSquare size={18} />
          </span>
          <div>
            <h2 className="font-display text-lg font-semibold text-paper">
              Draft your launch posts
            </h2>
            <p className="mt-1 max-w-xl text-sm text-paper-dim">
              Value-first posts for the communities where your users already
              gather — written for your app, ready to tailor and post.{" "}
              <span className="text-paper-faint">
                {live ? "Live AI." : "Generated by Wildgrow's engine."}
              </span>
            </p>
          </div>
        </div>
        <button
          onClick={draft}
          disabled={pending}
          className={cn(buttonVariants({}), "shrink-0")}
        >
          {pending ? (
            <Loader2 size={16} className="animate-spin" />
          ) : (
            <Sparkles size={16} />
          )}
          {posts ? "Regenerate" : "Draft posts"}
        </button>
      </div>

      {posts && posts.length > 0 && (
        <div className="mt-6 space-y-4">
          {posts.map((post, i) => (
            <div
              key={i}
              className="rounded-xl border border-line bg-ink-925 p-5"
            >
              <div className="flex items-center justify-between gap-3">
                <Badge tone="ember">{post.community}</Badge>
                <CopyButton
                  text={`${post.title}\n\n${post.body}`}
                  label="Copy post"
                />
              </div>
              <p className="mt-3 font-display text-base font-semibold text-paper">
                {post.title}
              </p>
              <p className="mt-2 whitespace-pre-line text-sm leading-relaxed text-paper-dim">
                {post.body}
              </p>
              {post.note && (
                <p className="mt-4 flex items-start gap-2 rounded-lg border border-ember/20 bg-ember/[0.06] px-3 py-2 text-xs leading-relaxed text-paper-soft">
                  <Lightbulb size={13} className="mt-0.5 shrink-0 text-ember" />
                  <span>{post.note}</span>
                </p>
              )}
            </div>
          ))}
        </div>
      )}

      {posts && posts.length === 0 && (
        <p className="mt-4 text-sm text-down">
          Couldn’t draft posts right now — try again.
        </p>
      )}
    </section>
  );
}
