import type { SocialCreator, SocialVideo } from "@/lib/types";

// Illustrative sample data. Swap the provider (SOCIAL_PROVIDER env) to pull
// live signals from an approved data source. Numbers are realistic but invented.

export const DEMO_CREATORS: (SocialCreator & { tags: string[] })[] = [
  {
    handle: "@focusflow",
    niche: "Productivity & focus apps",
    followers: 184000,
    avgViews: 220000,
    angle: "Aesthetic 'romanticize your deep work' demos with a calm voiceover.",
    tags: ["productivity", "focus", "app", "ai", "study"],
  },
  {
    handle: "@notion.nerd",
    niche: "Second brain / note-taking",
    followers: 312000,
    avgViews: 410000,
    angle: "Fast 'set this up in 60 seconds' template tutorials.",
    tags: ["productivity", "notes", "secondbrain", "app", "study"],
  },
  {
    handle: "@buildwithlena",
    niche: "Indie founder / build in public",
    followers: 78000,
    avgViews: 96000,
    angle: "Raw founder vlogs — revenue, failures, and shipping in public.",
    tags: ["buildinpublic", "startup", "app", "indiehacker"],
  },
  {
    handle: "@deepworkdaily",
    niche: "Focus & ADHD tools",
    followers: 142000,
    avgViews: 130000,
    angle: "ADHD-friendly tips that quietly feature the tools she uses.",
    tags: ["adhd", "focus", "productivity", "app"],
  },
  {
    handle: "@themoneymentor",
    niche: "Personal finance apps",
    followers: 521000,
    avgViews: 600000,
    angle: "POV money skits that end on a budgeting app demo.",
    tags: ["finance", "money", "budgeting", "app"],
  },
  {
    handle: "@gymtechguy",
    niche: "Fitness apps & wearables",
    followers: 233000,
    avgViews: 280000,
    angle: "Before/after transformations tracked inside an app.",
    tags: ["fitness", "health", "app", "wearables"],
  },
  {
    handle: "@studywithmaya",
    niche: "Study & student tools",
    followers: 405000,
    avgViews: 350000,
    angle: "Study-with-me + 'apps that got me through finals'.",
    tags: ["study", "education", "productivity", "app"],
  },
  {
    handle: "@aitoolfinds",
    niche: "AI tools & apps",
    followers: 268000,
    avgViews: 480000,
    angle: "'You're using AI wrong' rapid-fire tool demos.",
    tags: ["ai", "tools", "app", "productivity"],
  },
  {
    handle: "@calmwithcam",
    niche: "Sleep & wellness apps",
    followers: 119000,
    avgViews: 175000,
    angle: "Soothing night-routine content with a wind-down app.",
    tags: ["health", "wellness", "sleep", "app"],
  },
  {
    handle: "@theappguy",
    niche: "App reviews (all niches)",
    followers: 690000,
    avgViews: 540000,
    angle: "'Apps TikTok made me download' rapid reviews.",
    tags: ["app", "reviews", "productivity", "ai", "finance"],
  },
];

export const DEMO_VIDEOS: (SocialVideo & { tags: string[] })[] = [
  {
    id: "v1",
    creator: "@notion.nerd",
    platform: "tiktok",
    caption: "the only setup you need fr #notion #productivity",
    views: 1240000,
    likes: 198000,
    comments: 4200,
    postedDaysAgo: 6,
    format: "Screen demo",
    hook: "Stop overcomplicating your notes. Do this instead.",
    tags: ["productivity", "notes", "secondbrain", "app", "study"],
  },
  {
    id: "v2",
    creator: "@focusflow",
    platform: "tiktok",
    caption: "POV: you actually finished your to-do list 🧘 #focus",
    views: 842000,
    likes: 132000,
    comments: 2900,
    postedDaysAgo: 3,
    format: "POV",
    hook: "POV: you finally found an app that makes focusing feel good.",
    tags: ["productivity", "focus", "app", "ai"],
  },
  {
    id: "v3",
    creator: "@buildwithlena",
    platform: "instagram",
    caption: "month 4 of building my app in public 🛠️ #buildinpublic",
    views: 402000,
    likes: 61000,
    comments: 3100,
    postedDaysAgo: 9,
    format: "Talking head",
    hook: "I quit my job to build this app. Here's month 4.",
    tags: ["buildinpublic", "startup", "app", "indiehacker"],
  },
  {
    id: "v4",
    creator: "@deepworkdaily",
    platform: "tiktok",
    caption: "if your brain has 100 tabs open, watch this #adhd",
    views: 1890000,
    likes: 311000,
    comments: 8700,
    postedDaysAgo: 4,
    format: "Relatable rant",
    hook: "Your brain has as many tabs open as your browser, doesn't it.",
    tags: ["adhd", "focus", "productivity", "app"],
  },
  {
    id: "v5",
    creator: "@aitoolfinds",
    platform: "tiktok",
    caption: "you're using AI wrong (3 tools) #aitools",
    views: 2310000,
    likes: 402000,
    comments: 11200,
    postedDaysAgo: 2,
    format: "Listicle",
    hook: "3 AI tools that feel illegal to know — #3 changed my week.",
    tags: ["ai", "tools", "app", "productivity"],
  },
  {
    id: "v6",
    creator: "@themoneymentor",
    platform: "tiktok",
    caption: "me explaining my budget to my bank account 💀 #money",
    views: 980000,
    likes: 154000,
    comments: 3600,
    postedDaysAgo: 7,
    format: "Skit",
    hook: "POV: your bank account after another 'small' treat.",
    tags: ["finance", "money", "budgeting", "app"],
  },
  {
    id: "v7",
    creator: "@studywithmaya",
    platform: "instagram",
    caption: "the apps that got me through finals 📚 #studytok",
    views: 670000,
    likes: 98000,
    comments: 2100,
    postedDaysAgo: 11,
    format: "Listicle",
    hook: "The 3 apps that got me through finals (free).",
    tags: ["study", "education", "productivity", "app"],
  },
  {
    id: "v8",
    creator: "@gymtechguy",
    platform: "tiktok",
    caption: "30 days, tracked. the difference is wild 💪 #fitness",
    views: 1120000,
    likes: 187000,
    comments: 4400,
    postedDaysAgo: 5,
    format: "Before/after",
    hook: "I tracked everything for 30 days. Here's the before vs after.",
    tags: ["fitness", "health", "app", "wearables"],
  },
  {
    id: "v9",
    creator: "@theappguy",
    platform: "tiktok",
    caption: "apps tiktok made me download pt.7 #apps",
    views: 1530000,
    likes: 241000,
    comments: 6300,
    postedDaysAgo: 1,
    format: "Reply to comment",
    hook: "Replying to 'best app you've never heard of' — this one.",
    tags: ["app", "reviews", "productivity", "ai", "finance"],
  },
  {
    id: "v10",
    creator: "@calmwithcam",
    platform: "instagram",
    caption: "my 9pm wind-down routine 🌙 #sleep #wellness",
    views: 540000,
    likes: 79000,
    comments: 1500,
    postedDaysAgo: 8,
    format: "Story",
    hook: "I couldn't sleep for years. This 9pm routine fixed it.",
    tags: ["health", "wellness", "sleep", "app"],
  },
  {
    id: "v11",
    creator: "@focusflow",
    platform: "tiktok",
    caption: "the 2-minute setup that saved my work week ✨ #productivity",
    views: 760000,
    likes: 121000,
    comments: 2400,
    postedDaysAgo: 12,
    format: "Tutorial",
    hook: "This 2-minute setup deleted my need for 4 other apps.",
    tags: ["productivity", "focus", "app", "ai"],
  },
  {
    id: "v12",
    creator: "@buildwithlena",
    platform: "tiktok",
    caption: "replying to 'does anyone even use your app' 🥲 #startup",
    views: 910000,
    likes: 168000,
    comments: 5200,
    postedDaysAgo: 3,
    format: "Reply to comment",
    hook: "Replying to 'does anyone even use your app?' — let me show you.",
    tags: ["buildinpublic", "startup", "app", "indiehacker"],
  },
];
